# Generated by Django 5.0.6 on 2024-07-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_ram_product_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='os',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
