# Generated by Django 5.0.6 on 2024-07-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_os'),
    ]

    operations = [
        migrations.CreateModel(
            name='ghid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_logo', models.CharField(max_length=1024)),
            ],
        ),
    ]
