# Generated by Django 5.0.6 on 2024-07-11 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_ghid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ghid',
        ),
    ]
