# Generated by Django 5.0.6 on 2024-07-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_delete_ghid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cpu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='memory',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
