# Generated by Django 5.0.6 on 2024-07-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_cpu_product_display_product_lan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cpu',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='display',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='lan',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
