# Generated by Django 5.0.6 on 2024-07-13 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_cpu_alter_product_display_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='product',
            name='display',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lan',
        ),
        migrations.RemoveField(
            model_name='product',
            name='memory',
        ),
    ]
