# Generated by Django 5.0.6 on 2024-07-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_product_cpu_remove_product_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='memory',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
