# Generated by Django 5.0.6 on 2024-07-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.CharField(max_length=1028),
        ),
    ]
