# Generated by Django 5.0.6 on 2024-07-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_product_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cpu',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='lan',
            field=models.CharField(default='', max_length=50),
        ),
    ]
