# Generated by Django 5.0.6 on 2024-07-15 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_cpu_product_display_product_lan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='product',
            name='display',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lan',
        ),
    ]
