# Generated by Django 5.0.6 on 2024-08-28 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_product_cpu_remove_product_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
